### PR TITLE
Name potential processing folder according to plugin_package (fix #43)

### LINKED ISSUE #43: Different default name for processing folder
**Expected behaviour**
The name of the folder for the processing provider algorithm modules should be something else other than "processing" to avoid confusion with the PyQGIS package. 

**Current behaviour**
Currently said folder is called "processing". This may cause a conflict or confusion with the QGIS package.

**Describe alternatives you've considered**
Name the folder after the plugin name, for example "myqgisplugin_processing".

### PR DESCRIPTION
**Pull request by JuhoErvasti**
If processing provider and algorithm is included rename their folder after the plugin_package option, for example "myqgisplugin_processing". This is to avoid confusion and errors with the built-in PyQGIS 'processing' package.

### CODE REVIEW

**Review by LKajan — APPROVED** [review]

**Comment by nmaarnio** [comment]
The `provider.py` still tries to import `processing_algorithm.py` from a directory called `processing`. Should also be updated to `myqgisplugin_processing`.

**Comment by nmaarnio** [comment]
The `remove_processing_files()` in post_gen_project.py also is removing an incorrect directory and should be updated

**Comment by JuhoErvasti** [comment]
@nmaarnio I've prepared a fix for the post_gen_project.py but I'm not sure what you mean with the processing_algorithm.py.

```
from .processing_algorithm import ProcessingAlgorithm
```

I think the "processing" folder/package is not being referred to at all in the provider, since this is an relative import (the processing_algorithm.py being in the same folder). I haven't modified the name of the algorithm module.

**Comment by nmaarnio** [comment]
I noticed this while I was checking PR #41 and was in the corresponding branch. Now I switched to main and it seems the issue in the `provider.py` is not present there. I think there might have been some merging mistake in `modernize-template` since the processing directory's name is updated there, but `provider.py.j2` exists still there and does not match the new directory name.

**Comment by JuhoErvasti** [comment]
Ah okay, I see that now. I'm going to add a suggestion to #41 then.

**Pull request merged**
